/*CREATE TABLE*/

CREATE TABLE nombre_tabla (
    columna1 tipo_dato [restricciones],
    columna2 tipo_dato [restricciones],
    ...
);

CREATE TABLE USUARIOS (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(30),
    FECHA_NAC DATE DEFAULT CURRENT_DATE,
    EDAD COMPUTED BY (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM FECHA_NAC))
);

/*ALTER TABLE*/
ALTER TABLE usuarios ADD direccion VARCHAR(50);

ALTER TABLE usuarios ALTER COLUMN nombre TYPE VARCHAR(40);

ALTER TABLE usuarios DROP direccion;

ALTER TABLE usuarios ADD CONSTRAINT pk_usuarios PRIMARY KEY (ID);

ALTER TABLE usuarios DROP CONSTRAINT pk_usuarios;

/*DOMINIOS*/
CREATE DOMAIN nombre_dominio AS tipo_dato
  [DEFAULT valor_defecto]
  [NOT NULL]
  [CHECK (condición)]
  [CHARACTER SET conjunto]
  [COLLATE orden];

CREATE DOMAIN Dactivo AS CHAR(1)
  DEFAULT 'N'
  NOT NULL
  CHECK (VALUE IN ('S', 'N'));

CREATE TABLE usuarios (
  estado Dactivo
);

ALTER DOMAIN Dactivo SET DEFAULT 'S';
ALTER DOMAIN Dactivo DROP DEFAULT;

DROP DOMAIN Dactivo;

/*INDICES*/
CREATE [UNIQUE] [ASC|DESC] INDEX nombre_indice
ON nombre_tabla (columna1 [, columna2]);

CREATE INDEX idx_nombre ON usuarios (nombre);

CREATE UNIQUE INDEX idx_dni ON personas (dni);

CREATE INDEX idx_apellidos ON usuarios COMPUTED BY (UPPER(apellidos));

ALTER INDEX idx_nombre INACTIVE;
ALTER INDEX idx_nombre ACTIVE;

DROP INDEX idx_nombre;

/*CREATE DATABASE*/
CREATE DATABASE 'ruta_fichero'
  [USER 'usuario' [PASSWORD 'contraseña']]
  [PAGE_SIZE = tamaño]
  [DEFAULT CHARACTER SET conjunto_caracteres]
  [LENGTH = num_paginas [PAGES]]
  [FILE 'ruta_secundaria' ...]
  [DIFFERENCE FILE 'ruta_delta'];

CREATE DATABASE 'C:\datos\mi_base.fdb'
  PAGE_SIZE = 8192
  DEFAULT CHARACTER SET UTF8;

CREATE DATABASE 'localhost:C:\web\prueba.fdb'
  PAGE_SIZE = 8192
  DEFAULT CHARACTER SET ISO8859_1
  LENGTH = 250000 PAGES
  FILE 'D:\otros\prueba1.fd1' STARTING AT 250001;

/*ALTER DATABASE*/
ALTER DATABASE
  SET DEFAULT CHARACTER SET UTF8
  | ADD FILE 'nuevo_fichero' LENGTH = 10000 PAGES
  | ADD DIFFERENCE FILE 'ruta_dif'
  | DROP DIFFERENCE FILE
  | BEGIN BACKUP
  | END BACKUP
  | SET LINGER TO segundos
  | DROP LINGER;

-- Cambiar conjunto de caracteres por defecto
ALTER DATABASE SET DEFAULT CHARACTER SET UTF8;

-- Añadir un fichero secundario
ALTER DATABASE ADD FILE 'D:\otros\mas_datos.fdb' LENGTH = 20000 PAGES;

-- Activar backup seguro
ALTER DATABASE BEGIN BACKUP;

-- Establecer linger (conexión viva)
ALTER DATABASE SET LINGER TO 60;

/*VISTAS*/
CREATE VIEW nombre_vista [(columna1, columna2, ...)] AS
SELECT ... FROM ... WHERE ...;

CREATE VIEW CONS_USUARIOS (ID, NOMBRE) AS
SELECT ID, NOMBRE FROM USUARIOS WHERE ID < 1000;

ALTER VIEW nombre_vista AS SELECT ...;
CREATE OR ALTER VIEW nombre_vista AS SELECT ...;

DROP VIEW nombre_vista;

/*SECUENCIAS / GENERADORES*/
CREATE SEQUENCE nombre_generador;
-- o con valor inicial:
CREATE SEQUENCE nombre_generador START WITH 100;

SELECT NEXT VALUE FOR nombre_generador FROM RDB$DATABASE;

SELECT GEN_ID(nombre_generador, incremento) FROM RDB$DATABASE;

ALTER SEQUENCE nombre_generador RESTART WITH 1;

SET GENERATOR nombre_generador TO 500;

DROP SEQUENCE nombre_generador;