create domain d_id integer;
create domain d_dni  varchar(10);
create domain d_cadena20  varchar(20);
create domain d_cadena40  varchar(40);
create domain d_cadena60  varchar(60);
create domain d_cadena80  varchar(80);
create domain d_entero int;


create domain d_nif  varchar(10);

create domain d_fecha date;
create domain d_dinero decimal (9,2);

create domain d_Bolean  boolean;
create domain d_porcentaje decimal(5,2);
create domain d_sexo CHARACTER(1);


drop table socios;

create table socios (
 id_socio d_id generated by DEFAULT as IDENTITY not null,
 nif d_nif not null,
 nombre d_cadena60 not null,
 sexo d_sexo,
 direccion d_cadena80 not null,
 poblacion d_cadena40 not null
);
commit;

alter table socios 
	add constraint pk_socios
    primary key (id_socio);
      
    
create table viajes (
 id_viaje d_id generated by DEFAULT as IDENTITY,
 descripcion d_cadena80 not null,
 fecha d_fecha not null,
 total_presupuestado d_dinero not null,
 total_gastato d_dinero not null
);

alter table viajes
	add constraint pk_viajes
    primary key (id_viaje);
    
drop table agencias; 
create table agencias (
 id_agencia d_id generated by DEFAULT as IDENTITY,
 nif d_nif not null,
 nombre d_cadena60 not null,
 direccion d_cadena80 not null,
 poblacion d_cadena40 not null,
 total_base d_dinero not null,
 total_iva d_dinero not null
);

alter table agencias
	add constraint pk_agencias
    primary key (id_agencia);


create table cuotas (
 id_cuota d_id generated by default as identity not null,
 id_socio d_id not null,
 anio d_entero not null,
 mes d_entero not null,
 importe d_dinero not null, 
 fecha_pago d_fecha
);

alter table cuotas
	add constraint pk_cuotas
    primary key (id_cuota);
    
alter table cuotas
	add constraint fk_cuotas_socios
    FOREIGN KEY (id_socio) references socios(id_socio)
    on delete no ACTION
    on UPDATE CASCADE;
    
    
create table pagos (
 id_pago d_id generated by default as identity not null,
 id_socio d_id not null,
 id_viaje d_id not null,
  fecha_pago d_fecha not null,
 importe d_dinero not null
);

alter table pagos
	add constraint pk_pagos
    primary key (id_pago);
    
alter table pagos
	add constraint fk_pagos_socios
    FOREIGN KEY (id_socio) references socios(id_socio)
    on delete no ACTION
    on UPDATE CASCADE;
    
alter table pagos
	add constraint fk_pagos_viajes
    FOREIGN KEY (id_viaje) references viajes(id_viaje)
    on delete no ACTION
    on UPDATE CASCADE;


drop table facturas;    
create table facturas (
 id_factura d_id generated by default as identity not null,
 id_viaje d_id not null,
 id_agencia d_id not null,
 codigo d_cadena20 not null,
 descripcion d_cadena80 not null,
 importe_base d_dinero not null,
 importe_iva d_dinero not null
);

alter table facturas
	add constraint pk_facturas
    primary key (id_factura);
    
alter table facturas
	add constraint fk_facturas_viajes
    FOREIGN KEY (id_viaje) references viajes(id_viaje)
    on delete no ACTION
    on UPDATE CASCADE;
    
alter table facturas
	add constraint fk_facturas_agencias
    FOREIGN KEY (id_agencia) references agencias(id_agencia)
    on delete no ACTION
    on UPDATE CASCADE;
    
    
    SELECT *
FROM AGENCIAS a
WHERE EXISTS (
  SELECT 1
  FROM FACTURAS f
  WHERE f.id_agencia = a.id_agencia
  AND f.importe_iva > 300
);

select *
	from pagos;
    
    insert into agencias (nif, nombre, direccion, poblacion, total_base, total_iva)
    values ('A1111', 'agencia1', 'C/ Agencia 1', 'Loja', 0,0);
    
     insert into agencias (nif, nombre, direccion, poblacion, total_base, total_iva)
    values ('A2222', 'agencia2', 'C/ Agencia 2', 'Loja', 0,0);
    
     insert into agencias (nif, nombre, direccion, poblacion, total_base, total_iva)
    values ('B1111', 'agencia3', 'C/ Agencia 3', 'Campillos', 0,0);
    
     insert into agencias (nif, nombre, direccion, poblacion, total_base, total_iva)
    values ('B2222', 'agencia4', 'C/ Agencia 3', 'Campillos', 0,0);
    
     insert into agencias (nif, nombre, direccion, poblacion, total_base, total_iva)
    values ('C1111', 'agencia5', 'C/ Agencia 1', 'Archidona', 0,0);
    
     insert into agencias (nif, nombre, direccion, poblacion, total_base, total_iva)
    values ('C2222', 'agencia6', 'C/ Agencia 1', 'Archidona', 0,0);
    
     insert into agencias (nif, nombre, direccion, poblacion, total_base, total_iva)
    values ('A333333', 'agencia7', 'C/ Agencia 1', 'Archidona', 0,0);

    commit;
    
    
    select * 
    	from agencias;